### ISSUE TITLE
Compiling Hello World

### ISSUE THREAD

**Issue by saturn77** [sinclairrf/SSBCC#1]
What an excellent project, I was able to compile the LED blinker project with no issue. However, when compiling the hello world project, I get an error associated with the definitions of the inport and output

FATAL ERROR:  outport missing value at hello_world.9x8:18

I tried the following shown below, but it did not work. Thanks. James

PERIPHERAL      UART_Tx outport = 1-bit o_uart_tx O_UART_TX \
                        inport  = 1-bit i_uart_tx_busy I_UART_TX_BUSY \
                        baudmethod = G_CLK_FREQ_HZ/115200

**Comment by sinclairrf** [comment]
James,

Change "inport" to "outstatus"

Let me know if you use this for a project or if you have any other issues,
Rodney

**Comment by saturn77** [comment]
That worked! I changed the code to be: 

PORTCOMMENT     UART_Tx port
PERIPHERAL      UART_Tx outport=O_UART_TX \
                        outstatus=I_UART_TX_BUSY \
                        baudmethod=G_CLK_FREQ_HZ/115200

ASSEMBLY hello_world.s

What I would like to do is combine the .s files associated with the dual interrupt and the hello world to output a version number when queried by a dumb terminal, and then otherwise send status information every 100 Hz up to the terminal. This would be for an Artix-7 sort of housekeeping separate from the main RTL code. -James

**Comment by sinclairrf** [comment]
James,

One approach would be to modify the dual interrupt example to have a 
bi-directional UART, see core/9x8/peripheral/tb/UART for examples for this.

Then, look for the two characters '?' and '\n' for example, and return 
the version number when that string is encountered.

Otherwise, use the external interrupt, presumably from some event 
already present in your system, to drive the 100 Hz updates.

There's also a timer peripheral that can be used to generate 100 Hz 
events in a polled loop.

Rodney

**Comment by saturn77** [comment]
Rodney;  

After considering your suggestion some effort I put together the following. It's a basic query / response with the "?" as the query and FPGA Version information as response. The read_check_uart statement is essentially polling. I am new to Forth but giving it my best effort. 

Thanks. James

.main
  "Welcome to SmallSTACK Terminal Emulator!\n"
  :tx_loop1 .outport(O_UART_TX) .jumpc(tx_loop1,nop) drop

  ; Read the rx data from uart and push a duplicate  onto the stack, test if "?" to send response
  :read_check_uart .inport(I_UART_RX) dup "?" &  

  .jumpc(response_loop)
    .jump(read_check_uart) 
  :response_loop
    .call(version_msg) :tx_loop2 outport(O_UART_TX) .jumpc(tx_loop2,nop) drop 
  .jump(read_check_uart)

 .function version_msg
   "FPGA Version 1.234\n"
 .return

**Comment by sinclairrf** [comment]
James,

I've made a few corrections.

I generally put labels alone on a line so that they're more visible.  
The exceptions is loops such as the one you use to copy the string to 
the UART.

Rodney

**Comment by saturn77** [comment]
Rodney, Thanks for the help. I follow all your comments. 

In general, should the use of the N for null string precede all strings? 

This is pretty exciting, I am going to do a build for the Digilent Nexsys 4 board and test this query/response uart design out. Once successful, I will expand it to do some other hardware on the board such as I2C and seven segments. 

James

**Comment by sinclairrf** [comment]
James,

The README file describes the different string types.  I generally use 
the following:

   "xxx" is the 3 x-characters
   N"xxx" is 4 characters, 3 'x's and the termnating null character

The loop you're using:

   :loop .outport(O_UART_TX) .jumpc(loop,nop) drop

performs the loop as long as there's not a null character and then 
discards the null character.

If I have a byte I want to output, I'll do something like:

   ; copy the byte to the return stack
   dup >r
   ; put the null-terminated carriage-return line-feed on the data stack
   N"\r\n"
   ; get the byte to send and convert it to a 2-digit hex string
   r> .call(char__byte_to_2hex)
   ; pre-pend a descriptive message string (not null-terminated)
   "msg:  "

to construct the message (in reverse order because it's going on the 
data stack with the end of the message going onto the data stack 
first).  And then use the loop or a corresponding function to output the 
message.

Rodney

**Comment by sinclairrf** [comment]
James,

Did you wind up using SSBCC for your project?

Rodney

**Comment by saturn77** [comment]
I have struggled a bit with using string I/O, and it is more Forth 
related than anything. I still like the SSBCC system very much. I need 
more practice. So I haven't put it into the design yet. James
